<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
    <meta name="keywords" content="ens, cosmodic, scenar, let medical, scenar-therapy">
    <meta name="viewport" content="width=device-width">

    <title>“LET Medical” Research Lab | ENS</title>
    <script type="text/javascript" src="../../js/jquery-1.11.0.min.js"></script>
    <!---->
    <script src="../../js/scrollto.js" type="text/javascript"></script>  <!-- перелистывание до якорей-->
    <script src="../../js/owl.carousel.js"></script>
    <script type="text/javascript" src="../../js/script.js"></script>

    <link rel="stylesheet" href="../../css/owl.carousel.css" />
    <link rel="stylesheet" href="../../css/owl.theme.default.css" />
    <link rel="stylesheet" type="text/css" href="../../css/styleico.css">
    <link rel="stylesheet" type="text/css" href="../../css/style.css">


    <!--[if lt IE 9]>
    <script src="http://css3-mediaqueries-js.googlecode.com/files/css3-mediaqueries.js"></script>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
<header>
    <div class="header-left"></div>
    <div class="header-right"></div>
    <nav class="header-nav">
        <div class="header-nav__container">
            <div class="slicknav-menu1">
                <div class="slicknav-menu1__but"><span class="icon-bars"></span></div>
            </div>

            <div class="header-nav__logo">
                <a class="header-nav__logo1" href="../../index.phtml">
                    <img src="../../images/ens_logo.png" alt="ens">
                </a>
                <a class="header-nav__logo2" href="">
                    <img src="../../images/letmedical_white-small.png" alt="let medical">
                </a>
            </div>
            <ul id="header-nav__list" class="header-nav__wrap">
                <li class="header-nav__item header-nav__item1"><a class="header-nav__item-a" href="#">R&D Products</a>
                    <ul class="header-nav__list1-1">
                        <div class="content__container">
                            <li class="header-nav__item1-1">
                                <a class="header-nav__item-a header-nav__item1-1-a" href="../../../products/products.phtml">Devices</a>
                                <ul class="header-nav__list2-1">
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/ens/ens.phtml">ENS</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/Es735/ex735.phtml">Ex735 Slider x2</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/ex715/ex715.phtml">Ex715</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/ps705/ps705.phtml">PS705</a></li>
                                </ul>
                            </li>
                            <li class="header-nav__item1-1 header-nav__item1-1-2">
                                <a class="header-nav__item-a header-nav__item1-1-a" href="../../products/accessories/accessories.phtml">Accesories</a>
                                <ul class="header-nav__list2-2">
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/dx1/dx1.phtml">Electrode DX1</a><div class="header-nav__item-img header-nav__item-img1"></div> </li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/dx2/dx2.phtml">Electrode DX2</a><div class="header-nav__item-img header-nav__item-img2"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/emc01/emc01.phtml">Electrode EMC01</a><div class="header-nav__item-img header-nav__item-img3"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/oko/oko.phtml">Electrode OKO</a><div class="header-nav__item-img header-nav__item-img4"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ent01/ent01.phtml">Electrode ENT01</a><div class="header-nav__item-img header-nav__item-img5"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/tablet03/tablet03.phtml">Electrode Tablet03</a><div class="header-nav__item-img header-nav__item-img6"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/tablet02/tablet02.phtml">Electrode Tablet02</a><div class="header-nav__item-img header-nav__item-img7"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ec01/ec01.phtml">Electrode EC01</a><div class="header-nav__item-img header-nav__item-img8"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ev01/ev01.phtml">Electrode EV01(w)</a><div class="header-nav__item-img header-nav__item-img9"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ev01z/ev01z.phtml">Electrode EV01(z)</a><div class="header-nav__item-img header-nav__item-img10"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ev01o/ev01o.phtml">Electrode EV01(o)</a><div class="header-nav__item-img header-nav__item-img11"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/er01/er01.phtml">Electrode ER01</a><div class="header-nav__item-img header-nav__item-img12"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/cu/cu.phtml">Cooper electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ag/ag.phtml">Silver electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/au/au.phtml">Gold electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/case-smart-m/case-smart-m.phtml">Original case Smart M</a><div class="header-nav__item-img header-nav__item-img16"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/case-pocket-m/case-pocket-m.phtml">Original case Pocke M</a><div class="header-nav__item-img header-nav__item-img17"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/case-smart-l/case-smart-l.phtml">Original case Smart L</a><div class="header-nav__item-img header-nav__item-img18"></div></li>

                                </ul>

                            </li>
                        </div>
                    </ul>

                </li>
                <li class="header-nav__item"><a class="header-nav__item-a" class="header-nav__item-a" href="../../technology/technology.phtml">About Technology</a></li>
                <li class="header-nav__item"><a class="header-nav__item-a" class="header-nav__item-a" class="header-nav__active-work" href="../../history/history.phtml">History</a></li>
                <li class="header-nav__item"><a class="header-nav__item-a" class="header-nav__item-a" href="../../aboutus/aboutus.phtml">About Us</a></li>
                <li class="header-nav__item header-nav__lang-wrap">
                    <a class="header-nav__lang" href="#"><span class="lang-desktop">en</span><span class="lang-mob">in english</span></a>
                    <a class="header-nav__lang" href="#"><span class="lang-desktop">ru</span><span class="lang-mob">по-русски</span></a>
                </li>
            </ul>
        </div>
    </nav>
</header>
<nav class="hyst-nav__wrap">
    <div class="products-nav hyst-nav">
        <div class="products-nav__container hyst-nav__container">
            <div class="products-nav__left">
                <a class="products-nav__left-a" products-nav__left-ahref="../../history/1990s/1990s.phtml">2010's</a>
            </div>
            <div class="slicknav-menu">
                <div class="slicknav-menu__but"><span class="icon-angle-down"></span></div>
            </div>
            <ul id="products-nav__list" class="products-nav__right">
                <li class="products-nav__item hyst-nav__item"><a href="../../history/1970s/1970s.phtml">1970's</a></li>
                <li class="products-nav__item hyst-nav__item">
                    <a href="../../history/1980s/1980s.phtml">1980's</a>
                </li>
                <li class="products-nav__item hyst-nav__item"><a href="../../history/1990s/1990s.phtml">1990's</a>                </li>
                <li class="products-nav__item hyst-nav__item"><a href="../../history/2000s/2000s.phtml">2000's</a></li>
                <li class="products-nav__item hyst-nav__item"><a class="header-nav__active" href="../../history/2010s/2010s.phtml">2010's</a>
                    <div class="hyst-bot-nav">
                        <div class="hyst-bot-nav__container">
                            <div class="hyst-bot-nav__item"><a href="../../history/2010s/2010s.phtml" class="hyst-bot-nav__img hyst-bot-nav2010__img1" ></a></div>
                            <ul id="hyst-bot-nav__list" class="owl-carousel owl-theme products-nav__right">
                                <li class="hyst-bot-nav__item"><a href="#ex735slider"><div class="hyst-bot-nav__img hyst-bot-nav2010__img2"></div><p class="hyst-bot-nav__txt">EX735 Slider</p></a></li>
                                <li class="hyst-bot-nav__item"><a href="#ex715"><div class="hyst-bot-nav__img hyst-bot-nav2010__img3"></div><p class="hyst-bot-nav__txt">EX715</p></a></li>
                                <li class="hyst-bot-nav__item"><a href="#ex735x2"><div class="hyst-bot-nav__img hyst-bot-nav2010__img4"></div><p class="hyst-bot-nav__txt">EX735 Slider x2</p></a></li>
                                <li class="hyst-bot-nav__item"><a href="#ec01"><div class="hyst-bot-nav__img hyst-bot-nav2010__img5"></div><p class="hyst-bot-nav__txt">EC01</p></a></li>
                                <li class="hyst-bot-nav__item"><a href="#myoscendisplay-myoscenled"><div class="hyst-bot-nav__img hyst-bot-nav2010__img6"></div><p class="hyst-bot-nav__txt">Myoscen</p></a></li>
                                <li class="hyst-bot-nav__item"><a href="#myoscendisplay-myoscenled"><div class="hyst-bot-nav__img hyst-bot-nav2010__img7"></div><p class="hyst-bot-nav__txt">Myoscen</p></a></li>
                                <li class="hyst-bot-nav__item"><a href="#ex735x3"><div class="hyst-bot-nav__img hyst-bot-nav2010__img8"></div><p class="hyst-bot-nav__txt">EX735 Slider x3</p></a></li>
                                <li class="hyst-bot-nav__item"><a href="#dx1"><div class="hyst-bot-nav__img hyst-bot-nav2010__img9"></div><p class="hyst-bot-nav__txt">DX1</p></a></li>
                                <li class="hyst-bot-nav__item"><a href="#dx2"><div class="hyst-bot-nav__img hyst-bot-nav2010__img10"></div><p class="hyst-bot-nav__txt">DX2</p></a></li>
                                <li class="hyst-bot-nav__item"><a href="#ens"><div class="hyst-bot-nav__img hyst-bot-nav2010__img11"></div><p class="hyst-bot-nav__txt">ENS</p></a></li>
                                <li class="hyst-bot-nav__item"><a href="#emc01"><div class="hyst-bot-nav__img hyst-bot-nav2010__img12"></div><p class="hyst-bot-nav__txt">EMC01</p></a></li>
                                <li class="hyst-bot-nav__item"><a href="#ent01"><div class="hyst-bot-nav__img hyst-bot-nav2010__img13"></div><p class="hyst-bot-nav__txt">ENT01</p></a></li>
                                <li class="hyst-bot-nav__item"><a href="#oko"><div class="hyst-bot-nav__img hyst-bot-nav2010__img14"></div><p class="hyst-bot-nav__txt">OKO</p></a></li>
                            </ul>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div  class="content">
    <div  class="hyst-block-bigimg hyst-block1">
        <div class="content__container">
            <div class="hyst-block1__txt">
                <span class="hyst-block1__txt1">
                    ENS
                </span>
                <span class="hyst-block1__txt2">
                    2016
                </span>
            </div>
        </div>
    </div>
    <div class="hyst-block-2010s__1">
        <div class="content__container">
            <h2 id="ex735slider" class="content-h2">Modific became Slider <span class="hyst-block__year">2011</span></h2>
            <div class="hyst-block-2010s__img hyst-block-2010s__img1"></div>
            <p class="content-p">We have developed anew the EX735Ag device, which raised the standards of efficiency for professional devices to a much higher level: this is the first time we give the body exactly what it “asks” for — we have implemented a “sliding” technology where the acting impulse is “sliding” in and between SCENAR and COSMODIC ranges, in a fully automatic mode.</p>
            <p class="content-p">“Sliding” technology not just provides correct approach to treatment, but makes it a high-precision one. And enlarges treatment capabilities a lot.</p>
            <p class="content-p">The new device became also known as “Slider”.</p>
            <h2 id="ev01z" class="content-h2">Remote electrode for vaginal action, “one-sphere” version <span class="hyst-block__year">2012</span></h2>
            <div class="hyst-block-2010s__img hyst-block-2010s__img2"></div>
            <p class="content-p">Unlike its predecessor with 2 “balls”, this electrode is more mobile in use, as due to its construction, more movements of both the patient and electrode are allowed, in case of need. The electrode can be turned to different directions or moved within inside, to act on particular place or provide action on a larger area during a session. But this is not all…</p>
            <p class="content-p">Why making one more electrode when we already have one? Both electrodes are applied in the same place, but their purpose is different.</p>
            <p class="content-p">Two-sphere electrode is acting while forming vacuum cavity due to contraction of vaginal muscles. This allows the spheres to fit tightly to the vaginal walls. The effect of such action is most of all observed in treatment of diseases of genital organs and neighbouring organs, plus special antibacterial effect. Also improvement of vision was noticed.</p>
            <p class="content-p">Electrode with one “sphere” is more mobile, has bigger size and effect it produces is different — first of all, it balances hormonal state of a woman, which becomes obvious quite soon — by good-looking appearance and skin texture, psychological state and relaxation of the whole body. And this means — no headaches and other pains, no nervousness, anxiety and depression. All hormonal and age changes are balanced, immune system becomes stronger. </p>
            <h2 id="ex715" class="content-h2">Upgraded EX715Ag <span class="hyst-block__year">2012</span></h2>
            <div class="hyst-block-2010s__img hyst-block-2010s__img3"></div>
            <p class="content-p">The device was positioned as “amazing but not easy to love” (it caused two polar emotions — either loved or not) and was known as “a device for women”.</p>
            <p class="content-p">By the end of 2012 we presented a new upgraded version.</p>
            <p class="content-p">The upgrade included implementation of the latest developments which before were only used in professional models. New action technologies allow providing most beneficial effect on inner organs and nervous system. And well-known rejuvenation effect is now enhanced due to the use of the device together with vaginal and rectal electrode probes.</p>
            <p class="content-p">We simplified operation, left only 3 most optimal action modes, implemented a new system of COSMODIC action with microresonances. Now the device has new and easier to understand representation of the action on the screen. Construction durability was also enhanced.</p>
            <p class="content-p">We all try to treat the disease... but we never fancy that there is another way of recovery — we can rejuvenate the body and ipso facto get rid of diseases. This is the main task which the new 715 model is performing.</p>
            <h2 id="ex735x2" class="content-h2">EX735Ag Slider x2 <span class="hyst-block__year">2013</span></h2>
            <div class="hyst-block-2010s__img hyst-block-2010s__img4"></div>
            <p class="content-p">History develops in spiral and our technology is evolving the same way.</p>
            <p class="content-p">Two years later we have the famous Slider, but... twice as more complicated and, at the same time, simpler.</p>
            <p class="content-p">Now it has 4 ranges for the acting impulse to “slide” within and between and covers the whole spectrum of the low-frequency signals emitted by the body.</p>
            <p class="content-p">Simultaneous action through 2 channels with each of them being tuned individually.</p>
            <p class="content-p">Two times as many action modes — 16 modes instead of 8 (in professional version).</p>
            <p class="content-p">Now you can work simultaneously with 2 remote electrodes or with a remote electrode and electrode of the device, including vaginal/rectal electrode probes and the electrodes of the device.</p>
            <p class="content-p">And this can replace 2 professional devices at a time and allows working on two symmetrical areas consistently or individually. And this speeds up recovery.</p>
            <p class="content-p">Only 2 operating controls — the button and the scroll switch, which enable quick and easy access to the most important settings.</p>
            <p class="content-p">Being able to adjust the display for 2 — left-handers and right-handers, provides comfortable use for those who find it more convenient to work with left or right hand.</p>
            <p class="content-p">And one more “two” — 2 types of “ski” electrodes — standard and wide.</p>
            <p class="content-p">At the moment, this device represents the latest achievements of “LET Medical” in the field of equipment implementing efficient non-invasive technologies of medication-free restoration of health and well-being.</p>



        </div>
    </div>
    <div  class="hyst-block-2010s__2">
        <div class="content__container">
            <h2 id="ec01" class="content-h2">Remote electrode EC01 <span class="hyst-block__year">2013</span></h2>
        </div>
    </div>
    <div  class="hyst-block-bigimg hyst-block-2010s__3"></div>
    <div class="hyst-block-2010s__4">
        <div class="content__container">
            <h2 id="myoscendisplay-myoscenled" class="content-h2">Myoscen <span class="hyst-block__year">2014</span></h2>
            <p class="content-p">“LET Medical” tends to develop each model for some specific purpose, as this way it can produce maximum effect in the field it is intended for. But now, having spent 5 years on developing a new Myoscen version, we decided to depart from the rule and created two devices which are absolutely equal in effect of treatment — two Myoscens. Yes, they are equal, but only in the action modes used in the device and efficiency... and that is all! And what makes each of them special — is the difference.</p>
            <div class="hyst-block-2010s__wrap-img">
                <div class="hyst-block-2010s__img hyst-block-2010s__img5"></div>
                <div class="hyst-block-2010s__img hyst-block-2010s__img6"></div>
            </div>
            <p class="content-p">One version — quite impressive, two HD OLED displays. Here we have full range of individual settings in the menu, statistics, graphics of body reactions and dose completion, digital readings for professional use, timer of action and timer of the whole session, battery status, etc. Quite “jam-packed” device.</p>
            <div class="hyst-block-2010s__wrap-img">
                <div class="hyst-block-2010s__img hyst-block-2010s__img7"></div>
                <div class="hyst-block-2010s__img hyst-block-2010s__img8"></div>
            </div>
            <p class="content-p">Another version is quite “modest” — with LED indication. Very simple, only necessary things. Provides quick access to action modes and allows changing settings on the go. Body reaction, dosage, action energy level and even battery status are clearly displayed by LED indicators. Main advantage of this version is that you can quickly and easily operate it. It is very robust and consumes little energy, that is all you need to administer quick aid.</p>
            <p class="content-p">This is the first device with such a minimum of operating controls. Only one “wheel” — three-position switch.</p>
            <p class="content-p">We are proud of the electrodes in this device! They are made of steel which doesn’t contain nickel. As we know, nickel is not a healthy metal at all. But this is not all. The electrodes are detachable, they are fixed with the help of magnets and you can remove them easily for cleaning and disinfection.</p>
            <p class="content-p">The casing was designed in an “everyday carry” form.</p>
            <p class="content-p">The electronic system of the device enables implementation of COSMODIC technology within average range. This allows applying Myoscen for treatment of various diseases as a most universal device. But of course, it can’t treat everything, its main purpose is being a “home doctor”.</p>
            <p class="content-p">This device was developed by “LET Medical”, production is carried out by our manufacturing partner in Voronezh, headed by Fursov Gennady Yakovlevich.</p>
            <h2 id="ex735x3" class="content-h2">EX735 Slider x3 <span class="hyst-block__year">2016</span></h2>
            <div class="hyst-block-2010s__img hyst-block-2010s__img9"></div>
        </div>
    </div>
    <div  class="hyst-block-2010s__5">
        <div class="content__container">
            <h2 id="dx1" class="content-h2">Remote electrode probe DX1 <span class="hyst-block__year">2016</span></h2>
        </div>
    </div>
    <div  class="hyst-block-bigimg hyst-block-2010s__6"></div>
    <div  class="hyst-block-2010s__7">
        <div class="content__container">
            <h2 id="dx2" class="content-h2">Remote electrode probe DX2 <span class="hyst-block__year">2016</span></h2>
        </div>
    </div>
    <div  class="hyst-block-bigimg hyst-block-2010s__8"></div>
    <div  class="hyst-block-2010s__9">
        <div class="content__container">
            <h2 id="ens" class="content-h2">ENS <span class="hyst-block__year">2016</span></h2>
        </div>
    </div>
    <div  class="hyst-block-2010s__10">
        <div class="content__container">
        </div>
    </div>
    <div  class="hyst-block-2010s__11">
        <div class="content__container">
            <h2 id="emc01"class="content-h2">Remote electrode probe EMC01 <span class="hyst-block__year">2016</span></h2>
        </div>
    </div>
    <div  class="hyst-block-bigimg hyst-block-2010s__12"></div>
    <div  class="hyst-block-2010s__13">
        <div class="content__container">
            <h2 id="ent01" class="content-h2">Remote electrode probe ENT01 <span class="hyst-block__year">2016</span></h2>
        </div>
    </div>
    <div  class="hyst-block-bigimg hyst-block-2010s__14"></div>
    <div  class="hyst-block-2010s__15">
        <div class="content__container">
            <h2 id="oko" class="content-h2">Remote electrode probe OKO <span class="hyst-block__year">2016</span></h2>
        </div>
    </div>
    <div  class="hyst-block-bigimg hyst-block-2010s__16"></div>
</div>
<?php include_once '../../footer/footer.php'; ?>
<script>
    $(document).ready(function(){
        function windowSize(){
            if($(window).width() > 768){
                $('.owl-carousel').owlCarousel({

//        loop:true, //Зацикливаем слайдер
                    margin:00, //Отступ от элемента справа в 50px
                    nav:true, //Отключение навигации
//        autoplay:true, //Автозапуск слайдера
                    smartSpeed:1000, //Время движения слайда
                    autoplayTimeout:2000, //Время смены слайда
                    mouseDrag:true,
                    touchDrag:true,
                    navText:false,
                    dots:false,
                    responsive:{ //Адаптивность. Кол-во выводимых элементов при определенной ширине.
                        0:{
                        },
                        780:{
                            items:4
                        },
                        1000:{
                            items:5
                        }
                    }
                });

            }
        }
        $(window).load(windowSize); // при загрузке
        $(window).resize(windowSize)
    });
</script>

<script>
    $(document).ready(function(){
        navmenu('.hyst-nav__wrap');
    });
</script>
</body>
</html>