<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
    <meta name="keywords" content="ens, cosmodic, scenar, let medical, scenar-therapy">
    <meta name="viewport" content="width=device-width">

    <title>“LET Medical” Research Lab | ENS</title>
    <script type="text/javascript" src="../../../js/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="../../../js/script.js"></script>
    <link rel="stylesheet" type="text/css" href="../../../css/styleico.css">
    <link rel="stylesheet" type="text/css" href="../../../css/style.css">
</head>
<body>
<header>
    <div class="header-left"></div>
    <div class="header-right"></div>
    <nav class="header-nav">
        <div class="header-nav__container">
            <div class="slicknav-menu1">
                <div class="slicknav-menu1__but"><span class="icon-bars"></span></div>
            </div>

            <div class="header-nav__logo">
                <a class="header-nav__logo1" href="../../../index.phtml">
                    <img src="../../../images/ens_logo.png" alt="ens">
                </a>
                <a class="header-nav__logo2" href="../../../index.phtml">
                    <img src="../../../images/letmedical_white-small.png" alt="let medical">
                </a>
            </div>
            <ul id="header-nav__list" class="header-nav__wrap header-nav__list ">
                <li class="header-nav__item header-nav__item1"><a class="header-nav__item-a" href="../../../products/products.phtml">R&D Products</a>
                    <ul class="header-nav__list1-1">
                        <div class="content__container">
                            <li class="header-nav__item1-1">
                                <a class="header-nav__item-a header-nav__item1-1-a" href="../../products.phtml">Devices</a>
                                <ul class="header-nav__list2-1">
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../../products/ens/ens.phtml">ENS</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../../products/Es735/ex735.phtml">Ex735 Slider x2</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../../products/ex715/ex715.phtml">Ex715</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../../products/ps705/ps705.phtml">PS705</a></li>
                                </ul>
                            </li>
                            <li class="header-nav__item1-1 header-nav__item1-1-2">
                                <a class="header-nav__item-a header-nav__item1-1-a" href="../accessories.phtml">Accesories</a>
                                <ul class="header-nav__list2-2">
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../dx1/dx1.phtml">Electrode DX1</a><div class="header-nav__item-img header-nav__item-img1"></div> </li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../dx2/dx2.phtml">Electrode DX2</a><div class="header-nav__item-img header-nav__item-img2"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../emc01/emc01.phtml">Electrode EMC01</a><div class="header-nav__item-img header-nav__item-img3"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../oko/oko.phtml">Electrode OKO</a><div class="header-nav__item-img header-nav__item-img4"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../ent01/ent01.phtml">Electrode ENT01</a><div class="header-nav__item-img header-nav__item-img5"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../tablet03/tablet03.phtml">Electrode Tablet03</a><div class="header-nav__item-img header-nav__item-img6"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../tablet02/tablet02.phtml">Electrode Tablet02</a><div class="header-nav__item-img header-nav__item-img7"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../ec01/ec01.phtml">Electrode EC01</a><div class="header-nav__item-img header-nav__item-img8"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../ev01/ev01.phtml">Electrode EV01(w)</a><div class="header-nav__item-img header-nav__item-img9"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../ev01z/ev01z.phtml">Electrode EV01(z)</a><div class="header-nav__item-img header-nav__item-img10"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../ev01o/ev01o.phtml">Electrode EV01(o)</a><div class="header-nav__item-img header-nav__item-img11"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../er01/er01.phtml">Electrode ER01</a><div class="header-nav__item-img header-nav__item-img12"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../cu/cu.phtml">Cooper electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../ag/ag.phtml">Silver electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../au/au.phtml">Gold electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../case-smart-m/case-smart-m.phtml">Original case Smart M</a><div class="header-nav__item-img header-nav__item-img16"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../case-pocket-m/case-pocket-m.phtml">Original case Pocke M</a><div class="header-nav__item-img header-nav__item-img17"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../case-smart-l/case-smart-l.phtml">Original case Smart L</a><div class="header-nav__item-img header-nav__item-img18"></div></li>

                                </ul>
                            </li>
                        </div>
                    </ul>

                </li>
                <li class="header-nav__item"><a class="header-nav__item-a"  href="../../../technology/technology.phtml">About Technology</a></li>
                <li class="header-nav__item"><a class="header-nav__item-a"  href="../../../history/history.phtml">History</a></li>
                <li class="header-nav__item no-border"><a class="header-nav__item-a" href="../../../aboutus/aboutus.phtml">About Us</a></li>
                <li class="header-nav__item header-nav__lang-wrap no-border">
                    <a class="header-nav__lang" href="#"><span class="lang-desktop">en</span><span class="lang-mob">in english</span></a>
                    <a class="header-nav__lang" href="#"><span class="lang-desktop">ru</span><span class="lang-mob">по-русски</span></a>
                </li>
            </ul>

        </div>
    </nav>
</header>


<div class="content">
    <div class="acc1-block1">
        <div class="content__container">
            <p class="title-h1">
                Original case Smart M
            </p>
        </div>
    </div>
    <div class="content__container">
        <div class="acc1-block2 acc1-block2-img-case-smart-m"></div>
    </div>
    <div class="acc1-block3">
        <div class="content__container">
            <div class="ens-block14__txt ">
                <p class="ens-block14__title title-h1">
                    Description
                </p>
                <p class="ens-block14__p1">
                    Robust, light and elegant case is perfect for every-day use and storage of the device.
                    The case is made of genuine high-quality leather.
                </p>
            </div>
            <div class="ens-block14__txt ">
                <p class="ens-block14__title">
                    Compatibility
                </p>
                <p class="ens-block14__p1">
                    EX715Ag
                </p>
            </div>
        </div>
    </div>
</div>
<?php include_once '../../../footer/footer.php'; ?>
<script>
    $(document).ready(function(){
        navmenu('.products-nav');
//        navmenu('.tech-nav');

    });
</script>

</body>
</html>