<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
    <meta name="keywords" content="ens, cosmodic, scenar, let medical, scenar-therapy">
    <meta name="viewport" content="width=device-width">

    <title>“LET Medical” Research Lab | ENS</title>
    <script type="text/javascript" src="../js/jquery-1.11.0.min.js"></script>

    <script src="../js/scrollto.js" type="text/javascript"></script>  <!-- перелистывание до якорей-->
    <script type="text/javascript" src="../js/script.js"></script>
    <link rel="stylesheet" type="text/css" href="../css/styleico.css">
    <link rel="stylesheet" type="text/css" href="../css/style.css">

    <!--[if lt IE 9]>
    <script src="http://css3-mediaqueries-js.googlecode.com/files/css3-mediaqueries.js"></script>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
<header>
    <div class="header-left"></div>
    <div class="header-right"></div>
    <nav class="header-nav">
        <div class="header-nav__container">
            <div class="slicknav-menu1">
                <div class="slicknav-menu1__but"><span class="icon-bars"></span></div>
            </div>

            <div class="header-nav__logo">
                <a class="header-nav__logo1" href="../index.phtml">
                    <img src="../images/ens_logo.png" alt="ens">
                </a>
                <a class="header-nav__logo2" href="">
                    <img src="../images/letmedical_white-small.png" alt="let medical">
                </a>
            </div>
            <ul id="header-nav__list" class="header-nav__wrap">
                <li class="header-nav__item header-nav__item1"><a class="header-nav__item-a" href="#">R&D Products</a>
                    <ul class="header-nav__list1-1">
                        <div class="content__container">
                            <li class="header-nav__item1-1">
                                <a class="header-nav__item-a header-nav__item1-1-a" href="../products/products.phtml">Devices</a>
                                <ul class="header-nav__list2-1">
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../products/ens/ens.phtml">ENS</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../products/Es735/ex735.phtml">Ex735 Slider x2</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../products/ex715/ex715.phtml">Ex715</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../products/ps705/ps705.phtml">PS705</a></li>
                                </ul>
                            </li>
                            <li class="header-nav__item1-1 header-nav__item1-1-2">
                                <a class="header-nav__item-a header-nav__item1-1-a" href="../products/accessories/accessories.phtml">Accesories</a>
                                <ul class="header-nav__list2-2">
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/dx1/dx1.phtml">Electrode DX1</a><div class="header-nav__item-img header-nav__item-img1"></div> </li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/dx2/dx2.phtml">Electrode DX2</a><div class="header-nav__item-img header-nav__item-img2"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/emc01/emc01.phtml">Electrode EMC01</a><div class="header-nav__item-img header-nav__item-img3"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/oko/oko.phtml">Electrode OKO</a><div class="header-nav__item-img header-nav__item-img4"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/ent01/ent01.phtml">Electrode ENT01</a><div class="header-nav__item-img header-nav__item-img5"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/tablet03/tablet03.phtml">Electrode Tablet03</a><div class="header-nav__item-img header-nav__item-img6"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/tablet02/tablet02.phtml">Electrode Tablet02</a><div class="header-nav__item-img header-nav__item-img7"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/ec01/ec01.phtml">Electrode EC01</a><div class="header-nav__item-img header-nav__item-img8"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/ev01/ev01.phtml">Electrode EV01(w)</a><div class="header-nav__item-img header-nav__item-img9"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/ev01z/ev01z.phtml">Electrode EV01(z)</a><div class="header-nav__item-img header-nav__item-img10"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/ev01o/ev01o.phtml">Electrode EV01(o)</a><div class="header-nav__item-img header-nav__item-img11"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/er01/er01.phtml">Electrode ER01</a><div class="header-nav__item-img header-nav__item-img12"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/cu/cu.phtml">Cooper electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/ag/ag.phtml">Silver electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/au/au.phtml">Gold electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/case-smart-m/case-smart-m.phtml">Original case Smart M</a><div class="header-nav__item-img header-nav__item-img16"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/case-pocket-m/case-pocket-m.phtml">Original case Pocke M</a><div class="header-nav__item-img header-nav__item-img17"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/case-smart-l/case-smart-l.phtml">Original case Smart L</a><div class="header-nav__item-img header-nav__item-img18"></div></li>

                                </ul>

                            </li>
                        </div>
                    </ul>

                </li>

                <li class="header-nav__item"><a class="header-nav__item-a header-nav__active" href="../technology/technology.phtml">About Technology</a></li>
                <li class="header-nav__item"><a class="header-nav__item-a" href="../history/history.phtml">History</a></li>
                <li class="header-nav__item"><a class="header-nav__item-a" href="../aboutus/aboutus.phtml">About Us</a></li>
                <li class="header-nav__item header-nav__lang-wrap">
                    <a class="header-nav__lang" href="#"><span class="lang-desktop">en</span><span class="lang-mob">in english</span></a>
                    <a class="header-nav__lang" href="#"><span class="lang-desktop">ru</span><span class="lang-mob">по-русски</span></a>
                </li>
            </ul>
        </div>
    </nav>
</header>


<nav class="products-nav tech-nav">
    <div class="products-nav__container tech-nav__container">
        <div class="slicknav-menu">
            <div class="slicknav-menu__but"><span class="icon-angle-down"></span></div>
        </div>
        <ul id="products-nav__list" class="products-nav__right tech-nav__list">
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../technology/tens_scenar_cosmodic/tens_scenar_cosmodic.phtml">TENS, SCENAR, COSMODIC technologies</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../technology/not_all_secrets_of_scenar-cosmodic/not_all_secrets_of_scenar-cosmodic.phtml">Not all secrets of SCENAR-COSMODIC	</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../technology/what_is_scenar-therapy/what_is_scenar-therapy.phtml">What is SCENAR-therapy?</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../technology/using/using.phtml">Using SCENAR</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../technology/how_it_work/how_it_work.phtml">How it works</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../technology/medication-free_treatment/medication-free_treatment.phtml">Medication-free treatment</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../technology/transferring_to_a_different_level_of_health/transferring_to_a_different_level_of_health.phtml">Transferring to a different level of health</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../technology/old_good_ens03/old_good_ens03.phtml">Old good ENS-03</a></li>
        </ul>
    </div>
</nav>
<div class="content">
    <div class="tech-block1">
        <div class="content__container">
            <div class="tech-block1__left">
                <a href="tens_scenar_cosmodic.phtml ">
                    <p class="tech-block1__left__p1 title-mobile">
                        TENS, SCENAR, COSMODIC
                    </p>
                    <p class="tech-block1__left__p2 title-mobile">
                        technologies
                    </p>
                </a>
                <p class="tech-block1__left__p3 content-p1 content-p1-mobile">
                    Alexander Karasev, the founder of “LET Medical” Research Lab, has developed three generations of
                    technologies which allow restoring health without medications: TENS — technology of effective
                    pain-relief, SCENAR — technology of medication-free treatment, COSMODIC — technology of
                    medication-free regeneration and recovery...
                </p>
            </div>
            <div class="tech-block1__right">
                <div class="tech-block1__right-top">
                    <a href="not_all_secrets_of_scenar-cosmodic.phtml">
                        <p class="tech-block1__right__p1 title-mobile">
                            Not all secrets of
                        </p>
                        <p class="tech-block1__right__p2 title-mobile">
                            SCENAR-COSMODIC
                        </p>
                    </a>
                    <p class="tech-block1__right__p3 content-p1-mobile">
                        COSMODIC technology forms the same impulse as SCENAR, but...
                    </p>
                </div>
                <div class="tech-block1__right-bot">
                    <a href="what_is_scenar-therapy.phtml">
                        <p class="tech-block1__right__p1 title-mobile">
                            What is
                        </p>
                        <p class="tech-block1__right__p2 title-mobile">
                            SCENAR-therapy?
                        </p>
                    </a>
                    <p class="tech-block1__right__p3 content-p1-mobile">
                        One of the main principles of medicine that has been developed and studied for thousands of
                        years is mobilization of body inherent reserves while using minimum medications...
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="tech-block2">
        <a href="transferring_to_a_different_level_of_health.phtml">
            <div class="tech-block2__wrap">
                <div class="content__container">
                    <p class="tech-block2__p1 title-mobile">
                        Transferring to a different level of health
                    </p>
                    <p class="tech-block2__p2 content-p1-mobile">
                        The most sophisticated therapeutic “LET Medical” device for today is EX735Ag Slider x2. It is equipped
                        with many automated features which make the use of it easy and simple. It covers all known ranges of
                        acting neuroexcitatory impulses invented by “LET Medical”, from simple SCENAR-action and SCENAR-adaptive
                        action to new COSMODIC and COSMODIC-2...
                    </p>
                </div>
            </div>
        </a>
    </div>
    <div class="tech-block3">
        <div class="content__container">
            <div class="tech-block3__left">
                <a href="using.phtml" class="tech-block3__p1 title-mobile ">
                    Using SCENAR
                </a>
                <p class="tech-block3__p2 content-p1-mobile">
                    We offer various models — from first-aid, home and personal models, which can be easily operated
                    even by a lay person to administer first aid and help to keep up healthy every day...
                </p>
            </div>
            <div class="tech-block3__mid">
                <a href="how_it_work.phtml" class="tech-block3__p1 title-mobile">
                    How it works
                </a>
                <p class="tech-block3__p2 content-p1-mobile">
                    Skin is known to be able to regulate various physiological functions of the body. Ancient doctors
                    could manage pain and cramps, increase or decrease metabolism, accelerate or slow down the heart
                    rhythm through irritation of various reflex areas on the skin...
                </p>
            </div>
            <div class="tech-block3__right">
                <a href="medication-free_treatment.phtml" class="tech-block3__p1 title-mobile">
                    Medication-free treatment
                </a>
                <p class="tech-block3__p2 content-p1-mobile">
                    Now over 70% of patients suffer from chronic diseases. Modern European medicine evidently cannot
                    help in most cases.
                </p>
                <p class="tech-block3__p2 content-p1-mobile">
                    Many of us have experienced or observed situations when various medications not only failed to
                    cure the disease but caused negative after-effects...
                </p>
            </div>
        </div>
    </div>
    <div class="tech-block4">
        <div class="content__container">
            <a href="old_good_ens03.phtml" class="tech-block4__p1 title-mobile">Old good ENS-03</a>
            <div class="tech-block4__img"></div>
            <p class="tech-block4__p2 content-p1 content-p1-mobile">
                One of the most frequent questions being asked is what the difference is between our treatment
                technologies which we have developed during several decades. Some years ago, we posted an article
                “TENS, SCENAR, COSMODIC technologies” where we tried to tell about each technology, their development
                stages and further scenarios...
            </p>
        </div>
    </div>
</div>
<footer>
    <div class="footer-top">
        <div class="footer-container">
            <div class="footer-top__block footer-top__block1">
                <div class="footer-top__block1__ico"></div>
                <p class="footer-top__block1__txt">Research Laboratory of Medical Electronics
                   <br> “LET Medical”</p>
            </div>
            <div class="footer-top__block footer-top__block2">
                <p class="footer-top__block2__txt">
                    PATENTED
                    TECHNOLOGY
                </p>
            </div>
            <div class="footer-top__block footer-top__block3">
                <p class="footer-top__block3__txt1">
                    SCENAR-therapy
                </p>
                <a href="" class="footer-top__block3__txt2">
                    www.scenar-therapy.com
                </a>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="footer-container">
            <p class="footer-bottom__block">
                © 1990–2017 “LET Medical” Research Lab Taganrog, Russia
                tel./fax +7 8634 323-777 (11.30 AM — 6.00 PM Moscow time)
                All rights reserved.
            </p>
            <p class="footer-bottom__block">
                LET Medical®, SCENAR®, COSMODIC®, MYOSCEN®, ENS® are registered trademarks
                of ”LET Medical“ Research Lab LLC.
                Design and specifications subject to change without notice.
            </p>
        </div>
    </div>

</footer>

<script>
    $(document).ready(function(){
//        navmenu('.products-nav');
        navmenu('.tech-nav');
    });
</script>
</body>
</html>