<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
    <meta name="keywords" content="ens, cosmodic, scenar, let medical, scenar-therapy">
    <meta name="viewport" content="width=device-width">

    <title>“LET Medical” Research Lab | ENS</title>
    <script type="text/javascript" src="../../js/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="../../js/script.js"></script>
    <link rel="stylesheet" type="text/css" href="../../css/styleico.css">
    <link rel="stylesheet" type="text/css" href="../../css/style.css">

    <!--[if lt IE 9]>
    <script src="http://css3-mediaqueries-js.googlecode.com/files/css3-mediaqueries.js"></script>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
<header>
    <div class="header-left"></div>
    <div class="header-right"></div>
    <nav class="header-nav">
        <div class="header-nav__container">
            <div class="slicknav-menu1">
                <div class="slicknav-menu1__but"><span class="icon-bars"></span></div>
            </div>

            <div class="header-nav__logo">
                <a class="header-nav__logo1" href="../../index.phtml">
                    <img src="../../images/ens_logo.png" alt="ens">
                </a>
                <a class="header-nav__logo2" href="">
                    <img src="../../images/letmedical_white-small.png" alt="let medical">
                </a>
            </div>
            <ul id="header-nav__list" class="header-nav__wrap">
                <li class="header-nav__item header-nav__item1"><a class="header-nav__item-a" href="#">R&D Products</a>
                    <ul class="header-nav__list1-1">
                        <div class="content__container">
                            <li class="header-nav__item1-1">
                                <a class="header-nav__item-a header-nav__item1-1-a" href="../../products/products.phtml">Devices</a>
                                <ul class="header-nav__list2-1">
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/ens/ens.phtml">ENS</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/Es735/ex735.phtml">Ex735 Slider x2</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/ex715/ex715.phtml">Ex715</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/ps705/ps705.phtml">PS705</a></li>
                                </ul>
                            </li>
                            <li class="header-nav__item1-1 header-nav__item1-1-2">
                                <a class="header-nav__item-a header-nav__item1-1-a" href="../../products/accessories/accessories.phtml">Accesories</a>
                                <ul class="header-nav__list2-2">
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/dx1/dx1.phtml">Electrode DX1</a><div class="header-nav__item-img header-nav__item-img1"></div> </li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/dx2/dx2.phtml">Electrode DX2</a><div class="header-nav__item-img header-nav__item-img2"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/emc01/emc01.phtml">Electrode EMC01</a><div class="header-nav__item-img header-nav__item-img3"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/oko/oko.phtml">Electrode OKO</a><div class="header-nav__item-img header-nav__item-img4"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ent01/ent01.phtml">Electrode ENT01</a><div class="header-nav__item-img header-nav__item-img5"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/tablet03/tablet03.phtml">Electrode Tablet03</a><div class="header-nav__item-img header-nav__item-img6"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/tablet02/tablet02.phtml">Electrode Tablet02</a><div class="header-nav__item-img header-nav__item-img7"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ec01/ec01.phtml">Electrode EC01</a><div class="header-nav__item-img header-nav__item-img8"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ev01/ev01.phtml">Electrode EV01(w)</a><div class="header-nav__item-img header-nav__item-img9"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ev01z/ev01z.phtml">Electrode EV01(z)</a><div class="header-nav__item-img header-nav__item-img10"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ev01o/ev01o.phtml">Electrode EV01(o)</a><div class="header-nav__item-img header-nav__item-img11"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/er01/er01.phtml">Electrode ER01</a><div class="header-nav__item-img header-nav__item-img12"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/cu/cu.phtml">Cooper electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ag/ag.phtml">Silver electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/au/au.phtml">Gold electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/case-smart-m/case-smart-m.phtml">Original case Smart M</a><div class="header-nav__item-img header-nav__item-img16"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/case-pocket-m/case-pocket-m.phtml">Original case Pocke M</a><div class="header-nav__item-img header-nav__item-img17"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/case-smart-l/case-smart-l.phtml">Original case Smart L</a><div class="header-nav__item-img header-nav__item-img18"></div></li>

                                </ul>

                            </li>
                        </div>
                    </ul>

                </li>
                <li class="header-nav__item"><a class="header-nav__item-a header-nav__active" href="../../technology/technology.phtml">About Technology</a></li>
                <li class="header-nav__item"><a class="header-nav__item-a" href="../../history/history.phtml">History</a></li>
                <li class="header-nav__item"><a class="header-nav__item-a" href="../../aboutus/aboutus.phtml">About Us</a></li>
                <li class="header-nav__item header-nav__lang-wrap">
                    <a class="header-nav__lang" href="#"><span class="lang-desktop">en</span><span class="lang-mob">in english</span></a>
                    <a class="header-nav__lang" href="#"><span class="lang-desktop">ru</span><span class="lang-mob">по-русски</span></a>
                </li>
            </ul>
        </div>
    </nav>
</header>


<nav class="products-nav tech-nav">
    <div class="products-nav__container tech-nav__container">
        <div class="slicknav-menu">
            <div class="slicknav-menu__but"><span class="icon-angle-down"></span></div>
        </div>
        <ul id="products-nav__list" class="products-nav__right tech-nav__list">
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../technology/tens_scenar_cosmodic.phtml">TENS, SCENAR, COSMODIC technologies</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../technology/not_all_secrets_of_scenar-cosmodic.phtml">Not all secrets of SCENAR-COSMODIC	</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../technology/what_is_scenar-therapy.phtml">What is SCENAR-therapy?</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../technology/using.phtml">Using SCENAR</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a tech-nav__active" href="../technology/how_it_work.phtml">How it works</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../technology/medication-free_treatment.phtml">Medication-free treatment</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../technology/transferring_to_a_different_level_of_health.phtml">Transferring to a different level of health</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../technology/old_good_ens03.phtml">Old good ENS-03</a></li>
        </ul>
    </div>
</nav>
<div class="content">
    <div class="technology-block1 how-block1">
        <div class="content__container">
            <p class="technology-block1__p1 how-block1__p1 ">
                How it works
            </p>
        </div>
    </div>
    <div class="how-block2">
        <div class="content__container">
            <p class="content-p">
                Skin is known to be able to regulate various physiological functions of the body. Ancient doctors could
                manage pain and cramps, increase or decrease metabolism, accelerate or slow down the heart rhythm
                through irritation of various reflex areas on the skin.
            </p>
            <p class="content-p">
                The skin integuments can sense detailed information about all processes occurring in the internal
                organs. If you can process such information, you will have a clear picture of the state of the body.
                Skin can receive external information and react to irritation through mechanical action
                (e. g. acupuncture, massage), exposure to heat, electric current, magnetic field, biological field,
                laser or ultrasound. Skin can receive such information in the form of electric, optic, thermal,
                chemical, magnetic, mechanical and other signals, then process them and send them in encoded form to
                the regulating systems of the body.
            </p>
            <p class="content-p">
                Skin is interconnected with internal organs and systems of the body. Therefore, any malfunctions
                occurring in the organs or systems of the body also influence the skin condition. So the skin carries
                information about the condition of the sick organs or malfunctions of the body systems. We can influence
                the sick organs and malfunctions in the body from the outside through the skin, while acting upon the
                certain skin areas.
            </p>
            <p class="content-p">
                It is a known fact that the electrical conduction, capacity, temperature and sensitivity of the skin
                change when something is going wrong in the body.
            </p>
            <p class="content-p">
                Depending on the areas being irritated, body reactions upon the irritation are different. This happens
                because our nervous system can adjust the body functioning to the present environment the body lives in.
                The skin areas manifesting increased physiological activity are used for action during treatment of
                diseases with SCENAR-therapy.
            </p>
            <p class="content-p">
                SCENAR and COSMODIC devices act upon the body with short-pulse low-frequency signals when the electrodes
                contact skin. Parameters of the acting signal are set automatically according to the biological
                feedbacks. In other words, when the electrodes touch the skin, the device receives information about the
                body’s state. Depending on the condition of the body the device forms and sends neuro-like impulses to
                the body. These impulses carry information necessary for normal functioning of the body organ or system.
            </p>
            <p class="content-p">
                First of all, SCENAR and COSMODIC action is focused on normalization of the disordered functions of the
                body. The main objective here is providing harmony and stimulating the defensive forces and latent
                reserves of the body. In fact, it is not the device that treats your diseases, but your own body. It
                only helps the body to remember how the healthy organs should work and recover.
            </p>
        </div>
    </div>

</div>

<footer>
    <div class="footer-top">
        <div class="footer-container">
            <div class="footer-top__block footer-top__block1">
                <div class="footer-top__block1__ico"></div>
                <p class="footer-top__block1__txt">Research Laboratory of Medical Electronics
                   <br> “LET Medical”</p>
            </div>
            <div class="footer-top__block footer-top__block2">
                <p class="footer-top__block2__txt">
                    PATENTED
                    TECHNOLOGY
                </p>
            </div>
            <div class="footer-top__block footer-top__block3">
                <p class="footer-top__block3__txt1">
                    SCENAR-therapy
                </p>
                <a href="" class="footer-top__block3__txt2">
                    www.scenar-therapy.com
                </a>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="footer-container">
            <p class="footer-bottom__block">
                © 1990–2017 “LET Medical” Research Lab Taganrog, Russia
                tel./fax +7 8634 323-777 (11.30 AM — 6.00 PM Moscow time)
                All rights reserved.
            </p>
            <p class="footer-bottom__block">
                LET Medical®, SCENAR®, COSMODIC®, MYOSCEN®, ENS® are registered trademarks
                of ”LET Medical“ Research Lab LLC.
                Design and specifications subject to change without notice.
            </p>
        </div>
    </div>

</footer>

<script>
    $(document).ready(function(){
//        navmenu('.products-nav');
        navmenu('.tech-nav');
    });
</script>
</body>
</html>