<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
    <meta name="keywords" content="ens, cosmodic, scenar, let medical, scenar-therapy">
    <meta name="viewport" content="width=device-width">

    <title>“LET Medical” Research Lab | ENS</title>
    <script type="text/javascript" src="../../js/jquery-1.11.0.min.js"></script>

    <script src="../../js/scrollto.js" type="text/javascript"></script>  <!-- перелистывание до якорей-->
    <script type="text/javascript" src="../../js/script.js"></script>

    <link rel="stylesheet" type="text/css" href="../../css/styleico.css">
    <link rel="stylesheet" type="text/css" href="../../css/style.css">

    <!--[if lt IE 9]>
    <script src="http://css3-mediaqueries-js.googlecode.com/files/css3-mediaqueries.js"></script>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
<header>
    <div class="header-left"></div>
    <div class="header-right"></div>
    <nav class="header-nav">
        <div class="header-nav__container">
            <div class="slicknav-menu1">
                <div class="slicknav-menu1__but"><span class="icon-bars"></span></div>
            </div>

            <div class="header-nav__logo">
                <a class="header-nav__logo1" href="../../index.phtml">
                    <img src="../../images/ens_logo.png" alt="ens">
                </a>
                <a class="header-nav__logo2" href="">
                    <img src="../../images/letmedical_white-small.png" alt="let medical">
                </a>
            </div>
            <ul id="header-nav__list" class="header-nav__wrap">
                <li class="header-nav__item header-nav__item1"><a class="header-nav__item-a" href="#">R&D Products</a>
                    <ul class="header-nav__list1-1">
                        <div class="content__container">
                            <li class="header-nav__item1-1">
                                <a class="header-nav__item-a header-nav__item1-1-a" href="../../products/products.phtml">Devices</a>
                                <ul class="header-nav__list2-1">
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/ens/ens.phtml">ENS</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/Es735/ex735.phtml">Ex735 Slider x2</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/ex715/ex715.phtml">Ex715</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/ps705/ps705.phtml">PS705</a></li>
                                </ul>
                            </li>
                            <li class="header-nav__item1-1 header-nav__item1-1-2">
                                <a class="header-nav__item-a header-nav__item1-1-a" href="../../products/accessories/accessories.phtml">Accesories</a>
                                <ul class="header-nav__list2-2">
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/dx1/dx1.phtml">Electrode DX1</a><div class="header-nav__item-img header-nav__item-img1"></div> </li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/dx2/dx2.phtml">Electrode DX2</a><div class="header-nav__item-img header-nav__item-img2"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/emc01/emc01.phtml">Electrode EMC01</a><div class="header-nav__item-img header-nav__item-img3"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/oko/oko.phtml">Electrode OKO</a><div class="header-nav__item-img header-nav__item-img4"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ent01/ent01.phtml">Electrode ENT01</a><div class="header-nav__item-img header-nav__item-img5"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/tablet03/tablet03.phtml">Electrode Tablet03</a><div class="header-nav__item-img header-nav__item-img6"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/tablet02/tablet02.phtml">Electrode Tablet02</a><div class="header-nav__item-img header-nav__item-img7"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ec01/ec01.phtml">Electrode EC01</a><div class="header-nav__item-img header-nav__item-img8"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ev01/ev01.phtml">Electrode EV01(w)</a><div class="header-nav__item-img header-nav__item-img9"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ev01z/ev01z.phtml">Electrode EV01(z)</a><div class="header-nav__item-img header-nav__item-img10"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ev01o/ev01o.phtml">Electrode EV01(o)</a><div class="header-nav__item-img header-nav__item-img11"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/er01/er01.phtml">Electrode ER01</a><div class="header-nav__item-img header-nav__item-img12"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/cu/cu.phtml">Cooper electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ag/ag.phtml">Silver electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/au/au.phtml">Gold electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/case-smart-m/case-smart-m.phtml">Original case Smart M</a><div class="header-nav__item-img header-nav__item-img16"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/case-pocket-m/case-pocket-m.phtml">Original case Pocke M</a><div class="header-nav__item-img header-nav__item-img17"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/case-smart-l/case-smart-l.phtml">Original case Smart L</a><div class="header-nav__item-img header-nav__item-img18"></div></li>

                                </ul>

                            </li>
                        </div>
                    </ul>

                </li>

                <li class="header-nav__item"><a class="header-nav__item-a header-nav__active" href="../../technology/technology.phtml">About Technology</a></li>
                <li class="header-nav__item"><a class="header-nav__item-a" href="../../history/history.phtml">History</a></li>
                <li class="header-nav__item"><a class="header-nav__item-a" href="../../aboutus/aboutus.phtml">About Us</a></li>
                <li class="header-nav__item header-nav__lang-wrap">
                    <a class="header-nav__lang" href="#"><span class="lang-desktop">en</span><span class="lang-mob">in english</span></a>
                    <a class="header-nav__lang" href="#"><span class="lang-desktop">ru</span><span class="lang-mob">по-русски</span></a>
                </li>
            </ul>
        </div>
    </nav>
</header>


<nav class="products-nav tech-nav">
    <div class="products-nav__container tech-nav__container">
        <div class="slicknav-menu">
            <div class="slicknav-menu__but"><span class="icon-angle-down"></span></div>
        </div>
        <ul id="products-nav__list" class="products-nav__right tech-nav__list">
            <li class="tech-nav__item"><a class="products-nav__item-a tech-nav__active" href="../../technology/tens_scenar_cosmodic/tens_scenar_cosmodic.phtml">TENS, SCENAR, COSMODIC technologies</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../../technology/not_all_secrets_of_scenar-cosmodic/not_all_secrets_of_scenar-cosmodic.phtml">Not all secrets of SCENAR-COSMODIC	</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../../technology/what_is_scenar-therapy/what_is_scenar-therapy.phtml">What is SCENAR-therapy?</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../../technology/using/using.phtml">Using SCENAR</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../../technology/how_it_work/how_it_work.phtml">How it works</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../../technology/medication-free_treatment/medication-free_treatment.phtml">Medication-free treatment</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../../technology/transferring_to_a_different_level_of_health/transferring_to_a_different_level_of_health.phtml">Transferring to a different level of health</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../../technology/old_good_ens03/old_good_ens03.phtml">Old good ENS-03</a></li>
        </ul>
    </div>
</nav>
<div class="content">
    <div class="tsc-block1">
        <div class="content__container">
           <p class="tsc-block1__p1">
               TENS, SCENAR, COSMODIC
           </p>
            <p class="tsc-block1__p2">
                technologies
            </p>
            <p class="tsc-block1__p3 content-p1">
                Alexander Karasev, the founder of “LET Medical” Research Lab, has developed three generations
                of technologies which allow restoring health without medications: TENS — technology of effective
                pain-relief, SCENAR — technology of medication-free treatment, COSMODIC — technology of medication-free
                regeneration and recovery.
            </p>
        </div>
    </div>
    <div class="tsc-block2">
        <div class="content__container">
            <h2 class="content-h2-center">
                TENS — technology of pain-relief
            </h2>
            <p class="content-p">
                TENS acts with the impulse which is more powerful and longer than the nerve signal of the pain.
                This way, it just suppresses pain signal and pain disappears, but returns after some time. Usually pain
                relieving effect lasts for about 20 minutes (here we mean serious pain, such as radiculitis, kidney
                colic, etc). TENS does not employ biofeedback.
            </p>
            <p class="content-p">
                First models of TENS devices were produced in 1975-80-s, they were TENS-01, TENS-02, TENS-02M.
            </p>
            <h2 class="content-h2-center">
                SCENAR — technology of treatment
            </h2>
            <p class="content-p">
                In this technology, the acting impulse changes dynamically during action (dynamic tuning in accordance
                with skin impedance) — shape and duration of the acting impulse are close by their characteristics to
                the impulse which after being distorted by skin layers, fat tissue, muscle tissues, etc., becomes
                similar to the nerve impulse. But the amplitude of the acting impulse is increased — this way the
                acting impulse artificially amplifies pathological signal. SCENAR is a “pain amplifier” (here “pain”
                means pain sensations, diseases, and other pathological conditions). It adjusts the dynamics of changes
                of its own signal to the dynamics of changes of condition of the “pain” zone. The body responds to this
                with amplified restorative reaction, as it interprets the artificially amplified pathological signal as
                a real one. This makes the body work out more powerful reaction to cope with the “pain”. To do that, you
                need at least one biofeedback to correct dynamics of changes of the impulse in accordance with dynamics
                of changes of the “pain” zone.
            </p>
            <p class="content-p">
                SCENAR technology allows restoring body functioning to the level it was functioning at before the
                disease occurred. SCENAR restores homeostasis which the body had before the disease.
            </p>
            <h2 class="content-h2-center">
                COSMODIC — technology of restoration
            </h2>
            <p class="content-p">
                With this technology the restorative function of the body is amplified directly, without amplifying
                the pathological signal. Here we need more complicated biofeedbacks which provide fine-tuning of the
                acting impulse in accordance with dynamics of the body reaction and not just in accordance with skin
                impedance. Diversity of the biofeedbacks allows involving both Central Nervous System and local
                regenerative abilities into restorative function. Now the packets of the acting impulses (not just
                single impulses) are regulated with biofeedbacks not only in accordance with dynamics of the signal
                (like in SCENAR) but also according to adjustment of the spectrum of the signal, to achieve maximum
                reaction of the CNS, and adjustment of interval dynamics of the packets of impulses, to involve local
                restorative mechanisms. Altogether, this process involves 46 biofeedbacks.
            </p>
            <p class="content-p">
                COSMODIC technology facilitates the ability of our body to restore itself at the cell level too.
                The body restores its functioning using both its general reserves (like in SCENAR) and own potential
                of its cells, which provides “rejuvenation” of the cells — restoration of their normal functioning.
                While facilitating the ability of our body to self-restore the healthy state at the cell level,
                theoretically COSMODIC cannot influence the biological age of a cell, but it can help the body to
                use the intrinsic, laid by Nature, abilities to heal itself.
            </p>
            <h2 class="content-h2-center tsc-block2__p4__border">
                “Active” SCENAR and “active” COSMODIC
            </h2>
            <p class="content-p">
                “Active” technologies of treatment (“active” SCENAR and “active” COSMODIC) are only yet implemented
                in the new professional model — EX735Ag.
            </p>
            <p class="content-p">
                In previous generations of devices SCENAR and COSMODIC technologies are “passive”. What does it mean?
                Every subsequent impulse is formed on the basis of analysis of body reaction to the previous acting
                impulse.
            </p>
            <p class="content-p">
                You can compare it to pushing the ball along the trampled down field — the ball will roll where it
                “wants” — into the nearest pit, for example. We can only give directions to the movement of the ball.
                It is the same with our body — you will only recover after you “push” the body forward to the “final
                destination point”. That is why we need many sessions, to “push” the body and help it “move” in right
                direction, as it is like a ball — can “roll off” to the side, in the direction of the nearest “pit”.
                That is the reason you cannot achieve the desired result quickly.
            </p>
            <div class="tsc-block2__border">
                <p class="content-p">
                    Summary. With the “passive” technology, when we act on the body, we receive information of
                    after effect of the impulse. This information is used to form the subsequent impulse, etc.
                    In other words, the information received from aftereffect of the previous impulse is used to
                    create the next impulse. This way we are 1 step behind.
                </p>
            </div>
            <p class="content-p">
                With the “active” technology, analysis of dynamics of changes of the body is based on reaction of the
                body upon several initial acting impulses. Knowing the dynamics, it is possible to make a forecast
                and make corrections into acting impulses, creating this way a “future” impulse. In other words, next
                impulses are formed not on the basis of body reaction to the previous impulse, but on the basis of
                extrapolation of the previous reactions.
            </p>
            <p class="content-p">
                This means, that now we are not “pushing” the ball, but take it in our hands and carry some distance
                forward, in the direction of “final destination point”. Sometimes we need to carry it several
                times — from one point to another (if the ball is too heavy or we have a long way to go), sometimes we
                can do it one time — carry the ball from point A to point B. thanks to such “active” technology, we can
                achieve the desired results of treatment much quicker.
            </p>
            <div class="tsc-block2__border">
                <p class="content-p">
                    Summary. With the “active” technology of treatment, the next impulse is formed on the basis of
                    extrapolation of body reaction to the several previous impulses, creating “future” impulse. This
                    way we may be several steps ahead.
                </p>
            </div>
            <div class="tsc-block2__p6-wrap">
                <p class="tsc-block2__p6">
                    COSMODIC is just a beginning...
                </p>
                <p class="tsc-block2__p6">
                    A. A. Karasev
                </p>
            </div>
        </div>
    </div>

</div>
<footer>
    <div class="footer-top">
        <div class="footer-container">
            <div class="footer-top__block footer-top__block1">
                <div class="footer-top__block1__ico"></div>
                <p class="footer-top__block1__txt">Research Laboratory of Medical Electronics
                   <br> “LET Medical”</p>
            </div>
            <div class="footer-top__block footer-top__block2">
                <p class="footer-top__block2__txt">
                    PATENTED
                    TECHNOLOGY
                </p>
            </div>
            <div class="footer-top__block footer-top__block3">
                <p class="footer-top__block3__txt1">
                    SCENAR-therapy
                </p>
                <a href="" class="footer-top__block3__txt2">
                    www.scenar-therapy.com
                </a>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="footer-container">
            <p class="footer-bottom__block">
                © 1990–2017 “LET Medical” Research Lab Taganrog, Russia
                tel./fax +7 8634 323-777 (11.30 AM — 6.00 PM Moscow time)
                All rights reserved.
            </p>
            <p class="footer-bottom__block">
                LET Medical®, SCENAR®, COSMODIC®, MYOSCEN®, ENS® are registered trademarks
                of ”LET Medical“ Research Lab LLC.
                Design and specifications subject to change without notice.
            </p>
        </div>
    </div>

</footer>

<script>
    $(document).ready(function(){
//        navmenu('.products-nav');
        navmenu('.tech-nav');
    });
</script>
</body>
</html>