<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
    <meta name="keywords" content="ens, cosmodic, scenar, let medical, scenar-therapy">
    <meta name="viewport" content="width=device-width">

    <title>“LET Medical” Research Lab | ENS</title>
    <script type="text/javascript" src="../js/jquery-1.11.0.min.js"></script>

    <script src="../js/scrollto.js" type="text/javascript"></script>  <!-- перелистывание до якорей-->
    <script type="text/javascript" src="../js/script.js"></script>

    <link rel="stylesheet" type="text/css" href="../css/styleico.css">
    <link rel="stylesheet" type="text/css" href="../css/style.css">

    <!--[if lt IE 9]>
    <script src="http://css3-mediaqueries-js.googlecode.com/files/css3-mediaqueries.js"></script>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
<header>
    <div class="header-left"></div>
    <div class="header-right"></div>
    <nav class="header-nav">
        <div class="header-nav__container">
            <div class="slicknav-menu1">
                <div class="slicknav-menu1__but"><span class="icon-bars"></span></div>
            </div>

            <div class="header-nav__logo">
                <a class="header-nav__logo1" href="index.phtml">
                    <img src="../images/ens_logo.png" alt="ens">
                </a>
                <a class="header-nav__logo2" href="">
                    <img src="../images/letmedical_white-small.png" alt="let medical">
                </a>
            </div>
            <ul id="header-nav__list" class="header-nav__wrap">
                <li class="header-nav__item header-nav__item1"><a class="header-nav__item-a" href="#">R&D Products</a>
                    <ul class="header-nav__list1-1">
                        <div class="content__container">
                            <li class="header-nav__item1-1">
                                <a class="header-nav__item-a header-nav__item1-1-a" href="../products/products.phtml">Devices</a>
                                <ul class="header-nav__list2-1">
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../products/ens/ens.phtml">ENS</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../products/Es735/ex735.phtml">Ex735 Slider x2</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../products/ex715/ex715.phtml">Ex715</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../products/ps705/ps705.phtml">PS705</a></li>
                                </ul>
                            </li>
                            <li class="header-nav__item1-1 header-nav__item1-1-2">
                                <a class="header-nav__item-a header-nav__item1-1-a" href="../products/accessories/accessories.phtml">Accesories</a>
                                <ul class="header-nav__list2-2">
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/dx1/dx1.phtml">Electrode DX1</a><div class="header-nav__item-img header-nav__item-img1"></div> </li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/dx2/dx2.phtml">Electrode DX2</a><div class="header-nav__item-img header-nav__item-img2"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/emc01/emc01.phtml">Electrode EMC01</a><div class="header-nav__item-img header-nav__item-img3"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/oko/oko.phtml">Electrode OKO</a><div class="header-nav__item-img header-nav__item-img4"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/ent01/ent01.phtml">Electrode ENT01</a><div class="header-nav__item-img header-nav__item-img5"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/tablet03/tablet03.phtml">Electrode Tablet03</a><div class="header-nav__item-img header-nav__item-img6"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/tablet02/tablet02.phtml">Electrode Tablet02</a><div class="header-nav__item-img header-nav__item-img7"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/ec01/ec01.phtml">Electrode EC01</a><div class="header-nav__item-img header-nav__item-img8"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/ev01/ev01.phtml">Electrode EV01(w)</a><div class="header-nav__item-img header-nav__item-img9"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/ev01z/ev01z.phtml">Electrode EV01(z)</a><div class="header-nav__item-img header-nav__item-img10"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/ev01o/ev01o.phtml">Electrode EV01(o)</a><div class="header-nav__item-img header-nav__item-img11"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/er01/er01.phtml">Electrode ER01</a><div class="header-nav__item-img header-nav__item-img12"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/cu/cu.phtml">Cooper electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/ag/ag.phtml">Silver electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/au/au.phtml">Gold electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/case-smart-m/case-smart-m.phtml">Original case Smart M</a><div class="header-nav__item-img header-nav__item-img16"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/case-pocket-m/case-pocket-m.phtml">Original case Pocke M</a><div class="header-nav__item-img header-nav__item-img17"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../products/accessories/case-smart-l/case-smart-l.phtml">Original case Smart L</a><div class="header-nav__item-img header-nav__item-img18"></div></li>

                                </ul>

                            </li>
                        </div>
                    </ul>

                </li>
                <li class="header-nav__item"><a class="header-nav__item-a"  href="../technology/technology.phtml">About Technology</a></li>
                <li class="header-nav__item"><a class="header-nav__item-a"  href="../history/history.phtml">History</a></li>
                <li class="header-nav__item"><a class="header-nav__item-a header-nav__active-work" href="../aboutus/aboutus.phtml">About Us</a></li>
                <li class="header-nav__item header-nav__lang-wrap">
                    <a class="header-nav__lang" href="#"><span class="lang-desktop">en</span><span class="lang-mob">in english</span></a>
                    <a class="header-nav__lang" href="#"><span class="lang-desktop">ru</span><span class="lang-mob">по-русски</span></a>
                </li>
            </ul>
        </div>
    </nav>
</header>


<nav class="products-nav hyst-nav">
    <div class="products-nav__container">
        <div class="products-nav__left about__left">
            <a class="products-nav__left-a" href="../index.phtml">ens.com</a>
        </div>
        <div class=" about__rigth">
            <a class="products-nav__item-a" href="legal/legal.phtml">Legal information</a></li>
        </div>
    </div>
</nav>

<div class="content">
    <div class="about-block1">
        <div class="content__container">
        </div>
    </div>
    <div class="about-block2">
        <div class="content__container">
            <h2 class="content-h2" >Research Laboratory of Medical Electronics<br>“LET Medical”</h2>
            <p class="content-p content-p1-mobile">Research Laboratory of Medical Electronics “LET Medical” LLC is a patent owner and developer of medical devices and technologies of medication-free treatment — SCENAR-therapy, COSMODIC-therapy and ENS-therapy.</p>
            <p class="content-p content-p1-mobile">The Research Lab was founded in Taganrog in 1990 by Alexander Karasev, the inventor of technologies for medication-free treatment — SCENAR, COSMODIC, ENS. </p>
            <p class="content-p content-p1-mobile">“LET&nbsp;Medical®”, “ЛЭТ&nbsp;Медикал®”, “COSMODIC®”, “КОСМОДИК®”, “SCENAR®”, “СКЭНАР®”, “MYOSCEN®”, “МИОСКЭН®” “ENS®”, “ЭНС®”, — are trademarks and service marks registered by “LET Medical”. </p>
            <p class="content-p content-p1-mobile">The Research Lab specializes in development of electronic equipment for medical and research purposes and also state-of-the-art non-invasive medication-free technologies of treatment and health recovery.</p>
            <div class="about-block1__background">
                <p class="content-h3">At present the Research Lab works in the following fields:</p>
                <ul class="content-p content-p1-mobile">
                    <li class="content-p1-mobile">R&amp;D in the field of electrostimulation, electrotherapy, magnetotherapy, phototherapy, wave therapy, resonance therapy and development of new trends and applications for SCENAR, COSMODIC and ENS therapy and SCENAR, COSMODIC and ENS cosmetology;</li>
                    <li class="content-p1-mobile">development of new prospective methods of diagnostics, prophylaxis, rehabilitation and medication-free treatment;</li>
                    <li class="content-p1-mobile">development and production of devices implementing technology of SCENAR-therapy, COSMODIC-therapy, ENS-therapy;</li>
                    <li class="content-p1-mobile">development and production of hardware-software complexes, mobile diagnostic systems;</li>
                    <li class="content-p1-mobile">development of training programs and multimedia systems in the field of medicine, production of training aids for SCENAR-COSMODIC therapists — in printed and electronic form (electronic textbooks, etc.).</li>
                </ul>
            </div>
            <p class="content-p content-p1-mobile">“LET Medical” Research Lab is the world’s leader in the field of technologies implementing SCENAR-therapy, COSMODIC-therapy and ENS-therapy.</p>
            <p class="content-p content-p1-mobile">“LET Medical” Research  Lab has developed a unique COSMODIC technology, which has no analogues in the world. “LET Medical” is an exclusive manufacturer of devices implementing this technology. </p>
            <p class="content-p content-p1-mobile">Recent years have been dedicated to the work on development and implementation of new treatment technology — ENS-therapy.</p>
            <p class="content-p content-p1-mobile">“LET Medical” has representatives and medical centres in Russia, UK, Canada, Australia, USA, Sweden, Greece, Japan.</p>
            <p class="content-p content-p1-mobile">All inventions of “LET&nbsp;Medical” Research Lab are protected by patents in Russia and abroad.</p>
            <p class="content-h3">Contact info:</p>
            <div class="about-block1__contact"">
                <p class="content-p content-p1-mobile">“LET Medical” Research  Lab, Taganrog, Russia<br><br>
                    tel./fax +7 8634 323-777 (11.30 AM – 6.00 PM Moscow time),<br>
                    e-mail: <a href="mailto:scenar@scenar.ru">scenar@scenar.ru</a></p>
            </div>
    </div>
</div>
<?php include_once '../footer/footer.php'; ?>

<script>
    $(document).ready(function(){
        navmenu('.hyst-nav');
//        navmenu('.tech-nav');
    });
</script>
</body>
</html>