<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
    <meta name="keywords" content="ens, cosmodic, scenar, let medical, scenar-therapy">
    <meta name="viewport" content="width=device-width">

    <title>“LET Medical” Research Lab | ENS</title>
    <script type="text/javascript" src="../../js/jquery-1.11.0.min.js"></script>

    <script src="../../js/scrollto.js" type="text/javascript"></script>  <!-- перелистывание до якорей-->
    <script type="text/javascript" src="../../js/script.js"></script>

    <link rel="stylesheet" type="text/css" href="../../css/styleico.css">
    <link rel="stylesheet" type="text/css" href="../../css/style.css">

    <!--[if lt IE 9]>
    <script src="http://css3-mediaqueries-js.googlecode.com/files/css3-mediaqueries.js"></script>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
<header>
    <div class="header-left"></div>
    <div class="header-right"></div>
    <nav class="header-nav">
        <div class="header-nav__container">
            <div class="slicknav-menu1">
                <div class="slicknav-menu1__but"><span class="icon-bars"></span></div>
            </div>

            <div class="header-nav__logo">
                <a class="header-nav__logo1" href="../../index.phtml">
                    <img src="../../images/ens_logo.png" alt="ens">
                </a>
                <a class="header-nav__logo2" href="">
                    <img src="../../images/letmedical_white-small.png" alt="let medical">
                </a>
            </div>
            <ul id="header-nav__list" class="header-nav__wrap">
                <li class="header-nav__item header-nav__item1"><a class="header-nav__item-a" href="#">R&D Products</a>
                    <ul class="header-nav__list1-1">
                        <div class="content__container">
                            <li class="header-nav__item1-1">
                                <a class="header-nav__item-a header-nav__item1-1-a" href="../../../products/products.phtml">Devices</a>
                                <ul class="header-nav__list2-1">
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/ens/ens.phtml">ENS</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/Es735/ex735.phtml">Ex735 Slider x2</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/ex715/ex715.phtml">Ex715</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/ps705/ps705.phtml">PS705</a></li>
                                </ul>
                            </li>
                            <li class="header-nav__item1-1 header-nav__item1-1-2">
                                <a class="header-nav__item-a header-nav__item1-1-a" href="../../products/accessories/accessories.phtml">Accesories</a>
                                <ul class="header-nav__list2-2">
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/dx1/dx1.phtml">Electrode DX1</a><div class="header-nav__item-img header-nav__item-img1"></div> </li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/dx2/dx2.phtml">Electrode DX2</a><div class="header-nav__item-img header-nav__item-img2"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/emc01/emc01.phtml">Electrode EMC01</a><div class="header-nav__item-img header-nav__item-img3"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/oko/oko.phtml">Electrode OKO</a><div class="header-nav__item-img header-nav__item-img4"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ent01/ent01.phtml">Electrode ENT01</a><div class="header-nav__item-img header-nav__item-img5"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/tablet03/tablet03.phtml">Electrode Tablet03</a><div class="header-nav__item-img header-nav__item-img6"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/tablet02/tablet02.phtml">Electrode Tablet02</a><div class="header-nav__item-img header-nav__item-img7"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ec01/ec01.phtml">Electrode EC01</a><div class="header-nav__item-img header-nav__item-img8"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ev01/ev01.phtml">Electrode EV01(w)</a><div class="header-nav__item-img header-nav__item-img9"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ev01z/ev01z.phtml">Electrode EV01(z)</a><div class="header-nav__item-img header-nav__item-img10"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ev01o/ev01o.phtml">Electrode EV01(o)</a><div class="header-nav__item-img header-nav__item-img11"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/er01/er01.phtml">Electrode ER01</a><div class="header-nav__item-img header-nav__item-img12"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/cu/cu.phtml">Cooper electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ag/ag.phtml">Silver electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/au/au.phtml">Gold electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/case-smart-m/case-smart-m.phtml">Original case Smart M</a><div class="header-nav__item-img header-nav__item-img16"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/case-pocket-m/case-pocket-m.phtml">Original case Pocke M</a><div class="header-nav__item-img header-nav__item-img17"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/case-smart-l/case-smart-l.phtml">Original case Smart L</a><div class="header-nav__item-img header-nav__item-img18"></div></li>

                                </ul>

                            </li>
                        </div>
                    </ul>

                </li>
                <li class="header-nav__item"><a class="header-nav__item-a" class="header-nav__item-a" href="../../technology/technology.phtml">About Technology</a></li>
                <li class="header-nav__item"><a class="header-nav__item-a" class="header-nav__item-a" class="header-nav__active-work" href="../../history/history.phtml">History</a></li>
                <li class="header-nav__item"><a class="header-nav__item-a" class="header-nav__item-a" href="../../aboutus/aboutus.phtml">About Us</a></li>
                <li class="header-nav__item header-nav__lang-wrap">
                    <a class="header-nav__lang" href="#"><span class="lang-desktop">en</span><span class="lang-mob">in english</span></a>
                    <a class="header-nav__lang" href="#"><span class="lang-desktop">ru</span><span class="lang-mob">по-русски</span></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

<nav class="hyst-nav__wrap">
    <div class="products-nav hyst-nav">
        <div class="products-nav__container hyst-nav__container">
            <div class="products-nav__left ">
                <a class="products-nav__left-a" href="../../history/1970s/1970s.phtml">1970's</a>
            </div>
            <div class="slicknav-menu">
                <div class="slicknav-menu__but"><span class="icon-angle-down"></span></div>
            </div>
            <ul id="products-nav__list" class="products-nav__right">
                <li class="products-nav__item hyst-nav__item">
                    <a class="header-nav__active" href="../../history/1970s/1970s.phtml">1970's</a>
                    <div class="hyst-bot-nav">
                        <div class="hyst-bot-nav__container">
                            <div class="hyst-bot-nav__item "><a class="hyst-bot-nav__img hyst-bot-nav__img1 " href="../../history/1970s/1970s.phtml"></a></div>
                            <ul id="hyst-bot-nav__list" class="products-nav__right">
                                <li class="hyst-bot-nav__item"><a href="#ens01"><div class="hyst-bot-nav__img hyst-bot-nav__img2"></div><p class="hyst-bot-nav__txt">ENS-1</p></a></li>
                                <li class="hyst-bot-nav__item"><a href="#ens02"><div class="hyst-bot-nav__img hyst-bot-nav__img3"></div><p class="hyst-bot-nav__txt">ENS-2</p></a></li>
                            </ul>
                        </div>
                    </div>
                </li>
                <li class="products-nav__item hyst-nav__item"><a href="../../history/1980s/1980s.phtml">1980's</a></li>
                <li class="products-nav__item hyst-nav__item"><a href="../../history/1990s/1990s.phtml">1990's</a></li>
                <li class="products-nav__item hyst-nav__item"><a href="../../history/2000s/2000s.phtml">2000's</a></li>
                <li class="products-nav__item hyst-nav__item"><a href="../../history/2010s/2010s.phtml">2010's</a></li>
            </ul>
        </div>
    </div>

</nav>

<div  class="content">
    <div  class="hyst-block-bigimg hyst-block9 hyst-block-top">
        <div class="content__container">
            <div class="hyst-block1__txt">
                <span class="hyst-block1__txt1">
                    ENS-01
                </span>
                <span class="hyst-block1__txt2">
                    1976
                </span>
            </div>
        </div>
    </div>
    <div class="hyst-block-1970s">
        <div class="content__container">
            <h2 class="content-h2">Idea <span class="hyst-block__year">1972</span></h2>
            <p class="content-p">
                In the early 1970-s, new methods of treatment started filtering through to the Soviet Union. These
                mainly were methods of ancient oriental medicine — reflexotherapy (needle reflexotherapy, acupuncture),
                which was then known as zhen-jui method.
            </p>
            <p class="content-p">
                Reflexotherapy (as you can see from the term) is a part of the treatment concept based on the principle
                of reflex — the most universal mechanism of nervous activity.
            </p>
            <p class="content-p">
                One of the main reasons why this method of treatment became so poplar was that it allowed treating
                diseases without medications or significantly reducing the use of medications.
            </p>
            <p class="content-p">
                Another important thing here is that with professional treatment there are no side-effects, while most
                medications cause them.
            </p>
            <p class="content-p">
                Such approach is only successful when applied by professional acupuncturists, but even in this case it
                does not guarantee 100% result. Self-treatment is, of course, out of the question.
            </p>
            <p class="content-p">
                Using reflex mechanisms for self-treatment is a very good idea. And it can be used for treatment of
                nearly all diseases. As any irritation is transmitted in our body in the form of nerve (electrical)
                impulses, it should be possible to make a universal “electrical” pill, why not? That is what Alexander
                Karasev was thinking about in 1972.
            </p>
            <h2 class="content-h2">Magneto <span class="year">1973</span></h2>
            <p class="content-p">
                The first device consisted of an engine (taken out of a children’s toy) with contact breaker. The engine
                broke the contacts, which were connected to the transformer with battery (like magneto in a tractor).
                The transformer was connected to the electrodes. Impulses, which were generated by contact break
                (self-induction) were close to the nerve impulses. When the electrodes were placed on the skin in the
                area of pain sensations you could achieve pain-relief effect. This device was the ancestor of all TENS
                devices (devices for pain-relief).
            </p>
            <p class="content-p">
                With time, the toy engine was replaced with generator, the contacts were replaced with electronic
                switch, and the transformer was left as it was. This is how a TENS was born. And all TENS devices are
                still made on the same principle.
            </p>
            <h2 id="ens01" class="content-h2">ENS-01 <span class="year">1976</span></h2>
            <div class="hyst-block-1970s__img1"></div>
            <p class="content-p">
                The first model for practical use.<br>
                Casing was made of ABS plastic sheet, glued with dichloroethane and decorated with leatherette.<br>
                Two slide controls — “energy” and “frequency”.<br>
                Electrode was round-shaped, coaxial. Detachable!!!<br>
                Indication: one LED displaying action energy level.<br>
                Power supply: built-in accumulators.
            </p>
            <h2 id="ens02" class="content-h2">ENS-02 <span class="year">1979</span></h2>
            <div class="hyst-block-1970s__img2"></div>
            <p class="content-p">
                This model was already made with digital chips.<br>
                Analog controls for energy and frequency regulation were replaced with two buttons — “increase” and
                “decrease” of energy level and the frequency was set with discrete switches with binary coding. The
                initial frequency could be increased from 1 to 16 times as much.<br>
                For the casing of this device two parts of the electric shaver “Mikma” casing were taken and joined
                together.
            </p>
        </div>
    </div>
</div>
<?php include_once '../../footer/footer.php'; ?>

<script>
    $(document).ready(function(){
        navmenu('.hyst-nav__wrap');
    });
</script>
</body>
</html>