<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
    <meta name="keywords" content="ens, cosmodic, scenar, let medical, scenar-therapy">
    <meta name="viewport" content="width=device-width">

    <title>“LET Medical” Research Lab | ENS</title>
    <script type="text/javascript" src="../../js/jquery-1.11.0.min.js"></script>

    <script src="../../js/scrollto.js" type="text/javascript"></script>  <!-- перелистывание до якорей-->
    <script type="text/javascript" src="../../js/script.js"></script>

    <link rel="stylesheet" type="text/css" href="../../css/styleico.css">
    <link rel="stylesheet" type="text/css" href="../../css/style.css">

    <!--[if lt IE 9]>
    <script src="http://css3-mediaqueries-js.googlecode.com/files/css3-mediaqueries.js"></script>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
<header>
    <div class="header-left"></div>
    <div class="header-right"></div>
    <nav class="header-nav">
        <div class="header-nav__container">
            <div class="slicknav-menu1">
                <div class="slicknav-menu1__but"><span class="icon-bars"></span></div>
            </div>

            <div class="header-nav__logo">
                <a class="header-nav__logo1" href="../../index.phtml">
                    <img src="../../images/ens_logo.png" alt="ens">
                </a>
                <a class="header-nav__logo2" href="">
                    <img src="../../images/letmedical_white-small.png" alt="let medical">
                </a>
            </div>
            <ul id="header-nav__list" class="header-nav__wrap">
                <li class="header-nav__item header-nav__item1"><a class="header-nav__item-a" href="#">R&D Products</a>
                    <ul class="header-nav__list1-1">
                        <div class="content__container">
                            <li class="header-nav__item1-1">
                                <a class="header-nav__item-a header-nav__item1-1-a" href="../../products/products.phtml">Devices</a>
                                <ul class="header-nav__list2-1">
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/ens/ens.phtml">ENS</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/Es735/ex735.phtml">Ex735 Slider x2</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/ex715/ex715.phtml">Ex715</a></li>
                                    <li class="header-nav__item2-1"><a class="header-nav__item-a" href="../../products/ps705/ps705.phtml">PS705</a></li>
                                </ul>
                            </li>
                            <li class="header-nav__item1-1 header-nav__item1-1-2">
                                <a class="header-nav__item-a header-nav__item1-1-a" href="../../products/accessories/accessories.phtml">Accesories</a>
                                <ul class="header-nav__list2-2">
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/dx1/dx1.phtml">Electrode DX1</a><div class="header-nav__item-img header-nav__item-img1"></div> </li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/dx2/dx2.phtml">Electrode DX2</a><div class="header-nav__item-img header-nav__item-img2"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/emc01/emc01.phtml">Electrode EMC01</a><div class="header-nav__item-img header-nav__item-img3"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/oko/oko.phtml">Electrode OKO</a><div class="header-nav__item-img header-nav__item-img4"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ent01/ent01.phtml">Electrode ENT01</a><div class="header-nav__item-img header-nav__item-img5"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/tablet03/tablet03.phtml">Electrode Tablet03</a><div class="header-nav__item-img header-nav__item-img6"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/tablet02/tablet02.phtml">Electrode Tablet02</a><div class="header-nav__item-img header-nav__item-img7"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ec01/ec01.phtml">Electrode EC01</a><div class="header-nav__item-img header-nav__item-img8"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ev01/ev01.phtml">Electrode EV01(w)</a><div class="header-nav__item-img header-nav__item-img9"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ev01z/ev01z.phtml">Electrode EV01(z)</a><div class="header-nav__item-img header-nav__item-img10"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ev01o/ev01o.phtml">Electrode EV01(o)</a><div class="header-nav__item-img header-nav__item-img11"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/er01/er01.phtml">Electrode ER01</a><div class="header-nav__item-img header-nav__item-img12"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/cu/cu.phtml">Cooper electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/ag/ag.phtml">Silver electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/au/au.phtml">Gold electrode</a><div class="header-nav__item-img header-nav__item-img13"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/case-smart-m/case-smart-m.phtml">Original case Smart M</a><div class="header-nav__item-img header-nav__item-img16"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/case-pocket-m/case-pocket-m.phtml">Original case Pocke M</a><div class="header-nav__item-img header-nav__item-img17"></div></li>
                                    <li class="header-nav__item2-2"><a class="header-nav__item-a" href="../../products/accessories/case-smart-l/case-smart-l.phtml">Original case Smart L</a><div class="header-nav__item-img header-nav__item-img18"></div></li>

                                </ul>

                            </li>
                        </div>
                    </ul>

                </li>

                <li class="header-nav__item"><a class="header-nav__item-a header-nav__active" href="../technology/technology.phtml">About Technology</a></li>
                <li class="header-nav__item"><a class="header-nav__item-a" href="../../history/history.phtml">History</a></li>
                <li class="header-nav__item"><a class="header-nav__item-a" href="../../aboutus/aboutus.phtml">About Us</a></li>
                <li class="header-nav__item header-nav__lang-wrap">
                    <a class="header-nav__lang" href="#"><span class="lang-desktop">en</span><span class="lang-mob">in english</span></a>
                    <a class="header-nav__lang" href="#"><span class="lang-desktop">ru</span><span class="lang-mob">по-русски</span></a>
                </li>
            </ul>
        </div>
    </nav>
</header>


<nav class="products-nav tech-nav">
    <div class="products-nav__container tech-nav__container">
        <div class="slicknav-menu">
            <div class="slicknav-menu__but"><span class="icon-angle-down"></span></div>
        </div>
        <ul id="products-nav__list" class="products-nav__right tech-nav__list">
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../../technology/tens_scenar_cosmodic/tens_scenar_cosmodic.phtml">TENS, SCENAR, COSMODIC technologies</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../../technology/not_all_secrets_of_scenar-cosmodic/not_all_secrets_of_scenar-cosmodic.phtml">Not all secrets of SCENAR-COSMODIC	</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../../technology/what_is_scenar-therapy/what_is_scenar-therapy.phtml">What is SCENAR-therapy?</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../../technology/using/using.phtml">Using SCENAR</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../../technology/how_it_work/how_it_work.phtml">How it works</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a tech-nav__active" href="../../technology/medication-free_treatment/medication-free_treatment.phtml">Medication-free treatment</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../../technology/transferring_to_a_different_level_of_health/transferring_to_a_different_level_of_health.phtml">Transferring to a different level of health</a></li>
            <li class="tech-nav__item"><a class="products-nav__item-a" href="../../technology/old_good_ens03/old_good_ens03.phtml">Old good ENS-03</a></li>
        </ul>
    </div>
</nav>
<div class="content">
    <div class="technology-block1 medic-block1">
        <div class="content__container">
            <p class="technology-block1__p1 medic-block1__p1">
                Medication-free treatment
            </p>
        </div>
    </div>
    <div class="medic-block2">
        <div class="content__container">
            <p class="content-p">
                Now over 70% of patients suffer from chronic diseases. Modern European medicine evidently cannot help
                in most cases.
            </p>
            <p class="content-p">
                Many of us have experienced or observed situations when various medications not only failed to cure the
                disease but caused negative after-effects. For example, the patient suffering from pneumonia is usually
                prescribed antipyretics, antibiotics, sulfanilamides, vitamins, and, sometimes, steroid hormones. After
                such treatment the patient “recovers” and is discharged as healthy. Often the doctor has no idea that
                the disease remained, because the body itself practically did not participate in conquering this
                condition.
            </p>
            <p class="content-p">
                If the patient has undergone several diseases treated like that, the body defence potential will be
                exhausted and the disease will become a chronic condition.
            </p>
            <p class="content-p">
                The main weak point of the European medicine consists in the fact that patients treated according to
                its methods usually suffer from a number of various disorders and have lots of popular patented drugs
                to be treated with but still remain in chronic condition and, consequently, have a grudge against the
                present-day medicine. This resulted in development of new medication-free methods of treatment
                worldwide.
            </p>
            <p class="content-p">
                Today the task of the doctors is not to prevent the body from fighting against the disease but help
                to regulate misbalanced adapting systems. More than twenty-year practice proved that SCENAR is an
                ideal implement to solve this problem.
            </p>
            <p class="content-p">
                The brain controls all organs and tissues by means of electric pulses. It follows, that we can act
                upon the body, internals and nervous system through skin using electric pulses, similar to the natural
                ones. SCENAR is the very device able to generate such electric pulses that are physiologically close to
                those imported to the brain.
            </p>
            <p class="content-p">
                The principle of operation of this device is based on forming impulses, similar to the nerve ones,
                modifying under the influence of body reaction. These modifications imitate brain functioning in the
                pathological area. Impulses formed this way increase production of aqueous equivalents of nucleic
                acids, DNA, RNA, proteins, and lipids thousands times as many. These equivalents imitate biologically
                active substances and are immediately spread by blood all over the body. As a result, the lost
                functions are restored just as quickly.
            </p>
            <p class="content-p">
                The only storage of information of active substances in a living body is DNA, i.&nbsp;e. source codes
                before the diseases occurred. Researches revealed that under certain conditions DNA is able to respond
                to external signals. Usual chaotic DNA fluctuations registered by laser correlation spectrography look
                like a complex sinusoid. But if influenced by the system of artificial commands, DNA turns into
                artificial trapezoidal function.
            </p>
            <p class="content-p">
                Adaptive regulators using neuro-like impulses for action are the most preferable means. Such
                regulators gain great popularity since this method is pain-free and does not require hypodermic
                penetration, that, in its turn, excludes any possibility of AIDS and hepatitis contamination.
            </p>
            <p class="content-p">
                Unlike present-day single-purpose medicine, SCENAR-therapy does not treat some particular organ but
                restores body malfunctions. Treatment of some certain pathology, as a rule, produces positive effect
                upon other disorders as well.
            </p>
            <p class="content-p">
                Of course, SCENAR is not a panacea for all conditions but it often helps those who failed to be cured
                by the methods of traditional medicine. That is why more and more people (and not only doctors) follow
                and support this trend. SCENAR-therapy finds application in new fields and new methods of treatment
                appear.
            </p>
            <p class="content-p">
                In Burdenko Institute of Neurosurgery SCENAR was successfully applied in treatment of complications
                after spinal cord injuries at different stages. In Research Institute of Children's Surgery,
                SCENAR-therapy promoted elimination of arrest of locomotor development in children. In Military
                Research Aviation Hospital SCENAR was used for treatment of central and peripheral nervous systems.
            </p>
            <p class="content-p">
                Of course, it is the doctor who should observe the processes in the body and provide the most effective
                treatment. However, SCENAR devices can be applied by anyone who is familiar with the manual and
                strictly follows the instructions on treatment. The devices can be used at home as well.
            </p>

        </div>
    </div>

</div>

<?php include_once '../../footer/footer.php'; ?>

<script>
    $(document).ready(function(){
//        navmenu('.products-nav');
        navmenu('.tech-nav');
    });
</script>
</body>
</html>